services:
  ride-sharing-backend:
    image: ${DOCKER_REGISTRY-}ridesharingbackend
    build:
      context: .
      dockerfile: Ride-Sharing-Backend\Dockerfile
    ports:
    - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development